### ISSUE TITLE
fix bug with dns resolution

### ISSUE THREAD

**Issue by ktsaou** [firehol/iprange#10]
@alonbl @philwhineray 

Can we release a new minor version that fixes an issue with DNS resolution?

This is the commit: https://github.com/firehol/iprange/commit/c95f44ec0a808f09a062ff83cd8d51729da9b66b

A line was missing.

**Comment by alonbl** [comment]
it is not a minor release but fix release (3rd component) :)

**Comment by philwhineray** [comment]
OK, I created and signed a 1.0.2 version.

I haven't announced it to the mailing list but everything should be in place.
