### ISSUE TITLE
Problem installing iprange

### ISSUE THREAD

**Issue by sLuvpreet33** [firehol/iprange#17]
I have downloaded the tar file file from github. 
Then after unzipping it, I am facing problem in` make && make install` 

Here is the error,

make  all-am
make[1]: Entering directory `/home/luvpreet/Downloads/iprange-1.0.3'
make[1]: Leaving directory `/home/luvpreet/Downloads/iprange-1.0.3'
make[1]: Entering directory `/home/luvpreet/Downloads/iprange-1.0.3'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c iprange '/usr/local/bin'
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 iprange.1 '/usr/local/share/man/man1'
make[1]: Leaving directory `/home/luvpreet/Downloads/iprange-1.0.3'

**Comment by philwhineray** [comment]
Your original message showed:

~~~~
usr/bin/install: cannot remove ‘/usr/local/bin/iprange’: Permission denied 
~~~~

Which seems to be missing in what can be seen above.

Anyway, you almost certainly need root permissions to install under `/usr/local` which is the default unless you specify a `--prefix` to the `./configure` step.

**Comment by sLuvpreet33** [comment]
I needed iprange for Fireqos. I got it(fireqos) installed. Thank you for helping.
