### ISSUE TITLE
Question: How to apply ipsets

### ISSUE THREAD

**Issue by sereeds** [firehol/iprange#22]
Let's say I have this example configuration, and I am using my own test ipset file, test1.netset.

ipv4 ipset create test1 hash:net
ipv4 ipset addfile test1 ipsets/test1.netset

ipv4 blacklist full ipset:test1

Let's say I have now added a new ip subnet to the file test1.netset.
What is the appropriate command to "reload" that ipset?

Is there a command to only reload the ipset?  
Should I also optimize the ip set after changing it?

**Comment by ktsaou** [comment]
You have 3 options:

1. You can use this script: https://github.com/firehol/firehol/blob/master/contrib/ipset-apply.sh - this standalone and it uses iprange to optimize the ipset.

2. `update-ipsets` does this automatically for the ipsets it manages.

3. For ipsets your firehol firewall knows (you have used it in the currently running firewall), you can use:

```sh
firehol ipset_update_from_file ipset_name filename
```

**Comment by sereeds** [comment]
Excellent information.  That is exactly what I was looking for.
Thank you very much.
