### ISSUE TITLE
cannot set CFLAGS

### ISSUE THREAD

**Issue by ktsaou** [firehol/iprange#3]
@alonbl if the user does:

```sh
make CFLAGS="-O3"
```

then it does not compile. You have to remember to do:

```sh
make CFLAGS="-O3 -pthreads"
```

Can we move `-pthreads` off the CFLAGS to allow the user overwrite optimizations?

**Comment by alonbl** [comment]
this is not the way to do this... correct:
```
./configure CFLAGS="-O3"
```

**Comment by ktsaou** [comment]
ok. thanks!
